// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cloudscribe.DynamicPolicy.Storage.EFCore.PostgreSql;

#nullable disable

namespace cloudscribe.DynamicPolicy.Storage.EFCore.PostgreSql.Migrations
{
    [DbContext(typeof(DynamicPolicyDbContext))]
    [Migration("20260403124531_cs-dynamic-policy-net10")]
    partial class csdynamicpolicynet10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.AllowedClaimValueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("allowed_value");

                    b.Property<Guid>("ClaimRequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_requirement_id");

                    b.HasKey("Id")
                        .HasName("pk_csp_auth_policy_claim_value");

                    b.HasIndex("ClaimRequirementId")
                        .HasDatabaseName("ix_csp_auth_policy_claim_value_claim_requirement_id");

                    b.ToTable("csp_auth_policy_claim_value", (string)null);
                });

            modelBuilder.Entity("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.AllowedRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedRole")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("allowed_role");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.HasKey("Id")
                        .HasName("pk_csp_auth_policy_role");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_csp_auth_policy_role_policy_id");

                    b.ToTable("csp_auth_policy_role", (string)null);
                });

            modelBuilder.Entity("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.AuthenticationSchemeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthenticationScheme")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("authentication_scheme");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.HasKey("Id")
                        .HasName("pk_csp_auth_policy_scheme");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_csp_auth_policy_scheme_policy_id");

                    b.ToTable("csp_auth_policy_scheme", (string)null);
                });

            modelBuilder.Entity("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.AuthorizationPolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<bool>("RequireAuthenticatedUser")
                        .HasColumnType("boolean")
                        .HasColumnName("require_authenticated_user");

                    b.Property<string>("RequiredUserName")
                        .HasColumnType("text")
                        .HasColumnName("required_user_name");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_csp_auth_policy");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_csp_auth_policy_tenant_id");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_csp_auth_policy_name_tenant_id");

                    b.ToTable("csp_auth_policy", (string)null);
                });

            modelBuilder.Entity("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.ClaimRequirementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClaimName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("claim_name");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.HasKey("Id")
                        .HasName("pk_csp_auth_policy_claim");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_csp_auth_policy_claim_policy_id");

                    b.ToTable("csp_auth_policy_claim", (string)null);
                });

            modelBuilder.Entity("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.AllowedClaimValueEntity", b =>
                {
                    b.HasOne("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.ClaimRequirementEntity", "ClaimRequirement")
                        .WithMany("AllowedValues")
                        .HasForeignKey("ClaimRequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_csp_auth_policy_claim_value_csp_auth_policy_claim_claim_requi");

                    b.Navigation("ClaimRequirement");
                });

            modelBuilder.Entity("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.AllowedRoleEntity", b =>
                {
                    b.HasOne("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.AuthorizationPolicyEntity", "Policy")
                        .WithMany("AllowedRoles")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_csp_auth_policy_role_csp_auth_policy_policy_id");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.AuthenticationSchemeEntity", b =>
                {
                    b.HasOne("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.AuthorizationPolicyEntity", "Policy")
                        .WithMany("AuthenticationSchemes")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_csp_auth_policy_scheme_csp_auth_policy_policy_id");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.ClaimRequirementEntity", b =>
                {
                    b.HasOne("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.AuthorizationPolicyEntity", "Policy")
                        .WithMany("RequiredClaims")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_csp_auth_policy_claim_csp_auth_policy_policy_id");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.AuthorizationPolicyEntity", b =>
                {
                    b.Navigation("AllowedRoles");

                    b.Navigation("AuthenticationSchemes");

                    b.Navigation("RequiredClaims");
                });

            modelBuilder.Entity("cloudscribe.DynamicPolicy.Storage.EFCore.Common.Entities.ClaimRequirementEntity", b =>
                {
                    b.Navigation("AllowedValues");
                });
#pragma warning restore 612, 618
        }
    }
}
